---
- hosts: jenkins_instance
  become: yes

  tasks:
    - name: Adding Ansible Repository in Ubuntu and install Ansible
      apt_repository:
        repo: "ppa:ansible/ansible"
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Kubernetes Setup
      block:
        - name: Install kubernetes packages
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - kubelet
            - kubeadm
            - kubectl

        - name: Initialize Kubernetes Master
          command: kubeadm init --apiserver-advertise-address=10.0.0.10 # Use the private IP of your Jenkins instance

        - name: Copy kube config to user directory
          command: "{{ item }}"
          loop:
            - mkdir -p $HOME/.kube
            - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            - chown $(id -u):$(id -g) $HOME/.kube/config

        - name: Deploy Pod network (Flannel)
          command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
