---
- name: Download Trivy Debian package
  get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
    dest: /tmp/trivy.deb

- name: Install Trivy
  apt:
    deb: /tmp/trivy.deb
    state: present
